### PR TITLE
improve high performance of news container

### PR DESCRIPTION
**Pull request by Huyeng**

### CODE REVIEW

**Comment by acorbi** [comment]
@Huyeng is this deployed on PP already? ping me when it is and I can tell you if it works better...

**Comment by kathi-aeviator** [comment]
@alex did you review that issue?

**Comment by acorbi** [comment]
@kathi-aeviator is it deployed? if it is ping me and I can test how performing it is now...

**Comment by alex** [comment]
Hi, I'm not the @alex you are looking for. Please reference @acorbi in the future.

**Comment by kathi-aeviator** [comment]
Sorry @alex for wrong comment. depends on bad mobile version of gitHub.

@Huyeng did you fixed that issue and deployed? On pp and staging same loading problems like in beginning. Please communicate on this.

**Pull request merged**
