### PR TITLE
Updates code to add the wms layer from geoserver

### PR DESCRIPTION
**Pull request by Huyeng**

### CODE REVIEW

**Comment by acorbi** [comment]
@Huyeng I understand this PR adds support for WMS layers to the map explorer and other JEO maps? wasn't it merged and deployed yet?

I will review, merge and deploy this PR, I see that it has come conflicts with the existing code base but should not be a problem....

**Comment by acorbi** [comment]
@Huyeng I have just done a commit with the changes needed for resolving the conflicts that existed on the functions.php file. This can be problematic because @chris-aeviator is working on the same files for the map explorer....

Can you please pull the latest change and test the code on your development environment? If it works, please tell me and I will merge it...

**Comment by Huyeng** [comment]
I have pulled the code, but it seems I don't see what I have done. Did you merge my code with yours?

**Comment by Huyeng** [comment]
I pull the Branch, but the map won't show up on the map exporer.
You can test it like the screen with the information below: 
screenshot_6
wms url: https://geoserver.opendevelopmentmekong.net/geoserver/wms?service=WMS
layer name: Testing:Test_mining
Then assign category for it. On the map explorer, if the map show up and clickable, then it works.

**Comment by acorbi** [comment]
ok, let me check

**Comment by acorbi** [comment]
@Huyeng I have been checking the code, both your first commit and mine thereafter, and testing it in my development machine with the same results as you indicate. I have tried with the data you have provided and with the one in this example https://wiki.state.ma.us/confluence/display/massgis/GeoServer+-+WMS+-+Simple+Example 

I can add the layer properly but when I want to display it in the map explorer nothing is shown. I have checked the debugger in the browser and I can see that the code is not calling any WMS endpoint so my assumption is that something is not being triggered.

Questions:
- Can you try to pull the code you opened the PR with, merge it into your local master and see if its still working for you? I can be that yours and the code developed on parallel have some conflicts...
- Can you check on the list of changes if you are missing anything you wrote? It could be that you have not pushed everything to the PR... For instance, the file inc/js/jeo.js where is it referenced from? I cannot see anything on opendev-theme calling that file...

The best would be to take 15 minutes together and debug this, I am sure we find a solution pretty quickly.

**Pull request closed without merging**
